### ISSUE TITLE
interesting project!

### ISSUE THREAD

**Issue by vxcall** [stacksm4sher/NotSoLethalCompany#1]
Hi, thanks for open sourcing an interesting project.

I've never interacted with mono-game with C++ therefore this looks attractive to learn from to me.
Since the logger bin is not there yet, i quickly coded/built my own and placed it yet the resulting `libNotSoLethalCompany.dll` refused to be injected to the process somehow.
I guess i fucked up with dll linking.

Anyways, Im looking forward to seeing this project to be completed by u and have some fun. 

# p.s.
successfully injected but there's a bug.

```cpp
void *hudManagerInstance = GetStaticFieldValue("HUDManager", "k__BackingField;", "", GAME_ASSEMBLY, 8);
```

I thought `k__BackingField;` here is supposed to be `Instance` or `<Instance>k__BackingField` ?
neither of them worked tho. Since HUDManager doesnt have other static members, idk what I'm meant to do.

<img width="500px" height="200px" src="https://github.com/stacksm4sher/NotSoLethalCompany/assets/33578715/298e61be-fd12-4ad7-8c20-245da7ba4b76"/>

**Comment by stacksm4sher** [comment]
Hi, glad to hear your feedback! :)

I'm already working on what you described, I'm currently stuck at work with a bunch of end-of-year tasks, but after the new year I'll commit fix changes!

**Comment by pseuxide** [comment]
Take your time buddy.

I ended up with using C# to scratch the surface of Mono game modding, it's way too easier than pulling it off with cpp. I realized using cpp is definitely a thing for people who has experience with C# modding and afford to do in a harder way.

I dont think I would do Mono modding with cpp in near future but I'm keen to see your fix! ( and dont forget to put the logger lib too man :laughing: )

**Comment by pseuxide** [comment]
Oh and i wanna share u an info about the game.

This game has a problem with camera.WorldToScreenPoint.
use WorldToScreenViewport and multiply window width and height. Refer to [this UC post](https://www.unknowncheats.me/forum/3921191-post32.html)

also Camera.main is tend to be nullptr I think.
So use localPlayer.gameplayCamera instead.

U may know already but I stuck at this badly so just wanna share it with u haha.
